events {}

http {
  client_max_body_size 20m;

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend:4000/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
      proxy_pass http://backend:4000/uploads/;
    }

    location / {
      proxy_pass http://frontend:80/;
      proxy_set_header Host $host;
    }
  }
}
